blank_issues_enabled: true
contact_links:
  - name: Community Discord
    url: https://discord.com/invite/microsoft-certification-study-group-676990910176821270
    about: Ask questions, get help, or discuss certifications with the community.
